import type { StyleFamily, StyleId } from "./types";

export const STYLE_OPTIONS: { id: StyleId; name: string }[] = [
  { id: "night-jade", name: "夜园玉蛇" },
  { id: "clay-candy", name: "软糖黏土" },
  { id: "obsidian-gold", name: "黑金珠宝" },
  { id: "cyber-neon", name: "赛博霓虹" },
  { id: "ink-wash", name: "水墨山水" },
  { id: "sea-salt", name: "海边盐风" },
  { id: "sakura-wa", name: "樱花和风" },
  { id: "magma", name: "熔岩黑曜" },
  { id: "aurora-snow", name: "雪原极光" },
  { id: "dunhuang", name: "敦煌壁画" },
];

export const CATALOG: Record<StyleId, StyleFamily> = {
  "night-jade": {
    id: "night-jade",
    label: "夜园玉蛇",
    english: "Night Garden",
    tone: "dark",
    snake: "jade",
    food: "peach",
    decor: "lanterns",
    bgImage: "/skins/night-jade.jpg",
    palette: {
      bg: "#071412",
      surface: "#0e221c",
      board: "#12261f",
      grid: "#1a332b",
      snake: "#3f8f72",
      snakeHi: "#c5e8c4",
      snakeLo: "#1d4a3a",
      head: "#d4b56a",
      food: "#e35a48",
      foodHi: "#f6c08a",
      text: "#e8f0e4",
      muted: "#7d968c",
      accent: "#d4b56a",
      glow: "#8fd4a4",
    },
    feel: { roundness: 0.86, glow: 0.55, metal: 0.25, cellGap: 0.12 },
    titles: ["夜园", "庭露", "月下"],
    subtitles: ["月下慢行", "露冷风轻", "灯影一寸"],
    foods: ["仙桃", "荔枝", "青梅"],
    deaths: ["露水干了", "月色散了", "庭院醒了"],
    starts: ["轻点开始", "步入庭中", "随月而行"],
  },
  "clay-candy": {
    id: "clay-candy",
    label: "软糖黏土",
    english: "Soft Clay",
    tone: "light",
    snake: "clay",
    food: "berry",
    decor: "sprinkles",
    bgImage: "/skins/clay-candy.jpg",
    palette: {
      bg: "#f3e4d4",
      surface: "#f7ebe0",
      board: "#f0d8c8",
      grid: "#e4c8b4",
      snake: "#7ec8a3",
      snakeHi: "#e8f6ee",
      snakeLo: "#4e9a78",
      head: "#f2a0b0",
      food: "#e85d6a",
      foodHi: "#ffc4b0",
      text: "#3a2a28",
      muted: "#8a7068",
      accent: "#d4786a",
      glow: "#ffd2c0",
    },
    feel: { roundness: 0.96, glow: 0.18, metal: 0.05, cellGap: 0.16 },
    titles: ["软糖", "黏土", "甜铺"],
    subtitles: ["慢慢咬一口", "刚出炉", "糖霜未干"],
    foods: ["草莓", "樱桃", "蜜柑"],
    deaths: ["糖霜化了", "烤箱叮了一声", "肚子圆了"],
    starts: ["开始揉面", "咬一口", "开动"],
  },
  "obsidian-gold": {
    id: "obsidian-gold",
    label: "黑金珠宝",
    english: "Obsidian",
    tone: "dark",
    snake: "gold",
    food: "gem",
    decor: "dust",
    bgImage: "/skins/obsidian-gold.jpg",
    palette: {
      bg: "#070708",
      surface: "#111114",
      board: "#0c0c0e",
      grid: "#1a1a1e",
      snake: "#c4a056",
      snakeHi: "#f3e3b8",
      snakeLo: "#6a4e22",
      head: "#eee6d2",
      food: "#c13a3a",
      foodHi: "#f0a0a0",
      text: "#f0ead8",
      muted: "#8a8070",
      accent: "#c4a056",
      glow: "#e8c878",
    },
    feel: { roundness: 0.42, glow: 0.4, metal: 0.92, cellGap: 0.1 },
    titles: ["黑金", "夜藏", "金鳞"],
    subtitles: ["只此一件", "灯下鉴宝", "静室"],
    foods: ["红宝", "祖母绿", "蓝宝石"],
    deaths: ["匣子合上了", "灯熄了一寸", "鉴定结束"],
    starts: ["开匣", "请鉴", "入室"],
  },
  "cyber-neon": {
    id: "cyber-neon",
    label: "赛博霓虹",
    english: "Neon Grid",
    tone: "dark",
    snake: "neon",
    food: "cube",
    decor: "scan",
    bgImage: "/skins/cyber-neon.jpg",
    palette: {
      bg: "#05060f",
      surface: "#0a1020",
      board: "#070b16",
      grid: "#122038",
      snake: "#3de0e8",
      snakeHi: "#c8ffff",
      snakeLo: "#167888",
      head: "#7af0ff",
      food: "#ff2f8e",
      foodHi: "#ffb0d8",
      text: "#e8f4ff",
      muted: "#6a88a8",
      accent: "#3de0e8",
      glow: "#3de0e8",
    },
    feel: { roundness: 0.28, glow: 0.95, metal: 0.55, cellGap: 0.08 },
    titles: ["霓虹", "夜航", "电光"],
    subtitles: ["雨后的街", "信号未断", "午夜频段"],
    foods: ["脉冲", "磁芯", "信标"],
    deaths: ["信号中断", "频段静了", "雨停了"],
    starts: ["接入", "上路", "点亮"],
  },
  "ink-wash": {
    id: "ink-wash",
    label: "水墨山水",
    english: "Ink Wash",
    tone: "light",
    snake: "ink",
    food: "seal",
    decor: "ink",
    bgImage: "/skins/ink-wash.jpg",
    palette: {
      bg: "#e6e1d4",
      surface: "#efe9da",
      board: "#e2dccb",
      grid: "#d2cbb8",
      snake: "#2a2a2a",
      snakeHi: "#6a6a6a",
      snakeLo: "#111111",
      head: "#1a1a1a",
      food: "#b42318",
      foodHi: "#e07060",
      text: "#1c1c1c",
      muted: "#7a7366",
      accent: "#b42318",
      glow: "#b42318",
    },
    feel: { roundness: 0.7, glow: 0.08, metal: 0.0, cellGap: 0.14 },
    titles: ["水墨", "远山", "一墨"],
    subtitles: ["留白之处", "淡墨千山", "纸未干"],
    foods: ["朱印", "朱砂", "落款"],
    deaths: ["墨干了", "卷起了", "山隐了"],
    starts: ["落笔", "开卷", "走笔"],
  },
  "sea-salt": {
    id: "sea-salt",
    label: "海边盐风",
    english: "Sea Salt",
    tone: "dark",
    snake: "glass",
    food: "shell",
    decor: "foam",
    bgImage: "/skins/sea-salt.jpg",
    palette: {
      bg: "#0c2430",
      surface: "#123040",
      board: "#153848",
      grid: "#1c4a58",
      snake: "#5ec4c0",
      snakeHi: "#d8f4f0",
      snakeLo: "#2a6e72",
      head: "#f0e6d0",
      food: "#e8906a",
      foodHi: "#ffd0b0",
      text: "#e8f2f0",
      muted: "#7aa0a4",
      accent: "#7ec8c4",
      glow: "#8ee0d8",
    },
    feel: { roundness: 0.88, glow: 0.45, metal: 0.35, cellGap: 0.13 },
    titles: ["盐风", "潮隙", "海玻璃"],
    subtitles: ["退潮之后", "风里有盐", "光落在壳上"],
    foods: ["海螺", "珊瑚", "盐晶"],
    deaths: ["潮回来了", "风停了一息", "壳空了"],
    starts: ["赤足", "随潮", "下滩"],
  },
  "sakura-wa": {
    id: "sakura-wa",
    label: "樱花和风",
    english: "Sakura",
    tone: "dark",
    snake: "lacquer",
    food: "blossom",
    decor: "petals",
    bgImage: "/skins/sakura-wa.jpg",
    palette: {
      bg: "#2a1820",
      surface: "#3a222c",
      board: "#321c26",
      grid: "#4a2c38",
      snake: "#d4788c",
      snakeHi: "#f8dce4",
      snakeLo: "#8a3e52",
      head: "#f0c8a0",
      food: "#f2b7c4",
      foodHi: "#ffe8ee",
      text: "#f8ece8",
      muted: "#b8989c",
      accent: "#e8b4a0",
      glow: "#f0c0cc",
    },
    feel: { roundness: 0.8, glow: 0.35, metal: 0.3, cellGap: 0.12 },
    titles: ["樱夜", "花见", "薄红"],
    subtitles: ["花比夜更短", "风过一树", "灯下花影"],
    foods: ["花瓣", "团子", "梅酒"],
    deaths: ["花落了", "夜深了", "风停了"],
    starts: ["入席", "看花", "举杯"],
  },
  magma: {
    id: "magma",
    label: "熔岩黑曜",
    english: "Magma",
    tone: "dark",
    snake: "magma",
    food: "ember",
    decor: "embers",
    bgImage: "/skins/magma.jpg",
    palette: {
      bg: "#100808",
      surface: "#1c1010",
      board: "#160c0c",
      grid: "#2a1612",
      snake: "#e07030",
      snakeHi: "#ffd090",
      snakeLo: "#7a2810",
      head: "#ffcc66",
      food: "#ff5a20",
      foodHi: "#ffc080",
      text: "#f8ece0",
      muted: "#a08070",
      accent: "#e07030",
      glow: "#ff8030",
    },
    feel: { roundness: 0.5, glow: 0.85, metal: 0.4, cellGap: 0.1 },
    titles: ["熔核", "黑曜", "烬"],
    subtitles: ["石心里的火", "尚未冷却", "岩缝一线"],
    foods: ["熔珠", "余烬", "火种"],
    deaths: ["火灭了一寸", "岩壳合上", "热散了"],
    starts: ["点燃", "入岩", "靠近"],
  },
  "aurora-snow": {
    id: "aurora-snow",
    label: "雪原极光",
    english: "Aurora",
    tone: "dark",
    snake: "ice",
    food: "crystal",
    decor: "snow",
    bgImage: "/skins/aurora-snow.jpg",
    palette: {
      bg: "#0a1220",
      surface: "#121c2c",
      board: "#0e1826",
      grid: "#1a283c",
      snake: "#7ee0c8",
      snakeHi: "#e8fff6",
      snakeLo: "#3a8878",
      head: "#c8b8ff",
      food: "#a8e0ff",
      foodHi: "#ffffff",
      text: "#eef4ff",
      muted: "#88a0b8",
      accent: "#9ae0d0",
      glow: "#b8fff0",
    },
    feel: { roundness: 0.74, glow: 0.7, metal: 0.55, cellGap: 0.12 },
    titles: ["极光", "雪原", "霜"],
    subtitles: ["天在呼吸", "雪还未醒", "北境无声"],
    foods: ["冰晶", "霜花", "极光尘"],
    deaths: ["光淡了", "雪停了", "夜更深了"],
    starts: ["踏雪", "仰望", "出发"],
  },
  dunhuang: {
    id: "dunhuang",
    label: "敦煌壁画",
    english: "Dunhuang",
    tone: "dark",
    snake: "mineral",
    food: "lotus",
    decor: "pigment",
    bgImage: "/skins/dunhuang.jpg",
    palette: {
      bg: "#2a1c10",
      surface: "#3a2818",
      board: "#322010",
      grid: "#4a3220",
      snake: "#c45c38",
      snakeHi: "#f0d0a0",
      snakeLo: "#7a3018",
      head: "#e8c878",
      food: "#d4a050",
      foodHi: "#ffe8b0",
      text: "#f4e8d0",
      muted: "#a08868",
      accent: "#d4a050",
      glow: "#e8c070",
    },
    feel: { roundness: 0.58, glow: 0.3, metal: 0.2, cellGap: 0.11 },
    titles: ["敦煌", "飞天", "石窟"],
    subtitles: ["壁上未干", "千年一色", "灯入窟中"],
    foods: ["莲花", "金箔", "朱砂"],
    deaths: ["灯尽了", "色淡了", "窟门合了"],
    starts: ["入窟", "点灯", "观壁"],
  },
};
